server:
  port: ${SERVER_PORT:8018}

spring:
  application:
    name: report-generator-v1

configuration:
  error-messages:
    Default: No hemos podido realizar tu operación. Estamos trabajando para solucionar el inconveniente.

  filePaths:
    prompts: prompts/prompts.json
    docx-template: /templates/template.docx

  rest-clients:
    openai-completion:
      endpoint: https://api.openai.com/v1/chat/completions
      headers:
        forwarded:
          channel-id: channel-id
        provided:
          Authorization: Bearer ${OPENAI_KEY}
      performance:
        timeout: ARTIFICIAL_INTELLIGENCE
        concurrency: MEDIUM
      configuration:
        max-tokens: 200 # response length
        temperature: 0.7 # creativity